# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2Createproject():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2Createproject(self):
    self.driver.get("https://redcap03.nottingham.ac.uk/redcap")
    self.driver.set_window_size(1078, 582)
    self.driver.find_element(By.LINK_TEXT, "New Project").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "app_title").send_keys("Clear PII Test")
    self.driver.find_element(By.ID, "purpose").click()
    dropdown = self.driver.find_element(By.ID, "purpose")
    dropdown.find_element(By.XPATH, "//option[. = 'Operational Support']").click()
    self.driver.find_element(By.ID, "project_template_radio2").click()
    self.driver.find_element(By.NAME, "odm").click()
    self.driver.find_element(By.NAME, "odm").send_keys("C:\\REDCap_test_Projects\\ClearPIITest_REDCap.xml")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primaryrc").click()
    self.driver.close()
  
