# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4SetupData():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_4SetupData(self):
    self.driver.get("https://redcap03.nottingham.ac.uk/redcap_v15.0.10/ProjectSetup/index.php?pid=532")
    self.driver.find_element(By.CSS_SELECTOR, "#rsd-men-link > span").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rcgreen:nth-child(1)").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".even > .nowrap:nth-child(3) img").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "opt-oth_pi_yes_no_1").click()
    self.driver.find_element(By.NAME, "oth_pi_non_id").click()
    self.driver.find_element(By.NAME, "oth_pi_non_id").send_keys("Test")
    self.driver.find_element(By.NAME, "oth_pi_id").click()
    self.driver.find_element(By.NAME, "oth_pi_id").send_keys("Test 2")
    self.driver.find_element(By.NAME, "oth_pi_complete").click()
    dropdown = self.driver.find_element(By.NAME, "oth_pi_complete")
    dropdown.find_element(By.XPATH, "//option[. = 'Complete']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\__SUBMITBUTTONS__-div > #submit-btn-saverecord > span").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".odd img").click()
    time.sleep(3)
    self.driver.find_element(By.NAME, "cd_name").click()
    self.driver.find_element(By.NAME, "cd_name").send_keys("Test Record 1")
    self.driver.find_element(By.NAME, "cd_email").click()
    self.driver.find_element(By.NAME, "cd_email").send_keys("nina.clayton@nottingham.ac.uk")
    self.driver.find_element(By.CSS_SELECTOR, "#cd_mobile-tr > .data").click()
    self.driver.find_element(By.NAME, "cd_mobile").click()
    self.driver.find_element(By.NAME, "cd_mobile").send_keys("07777888888")
    self.driver.find_element(By.CSS_SELECTOR, "#cd_complete-tr > .data").click()
    self.driver.find_element(By.NAME, "cd_complete").click()
    dropdown = self.driver.find_element(By.NAME, "cd_complete")
    dropdown.find_element(By.XPATH, "//option[. = 'Complete']").click()
    self.driver.find_element(By.ID, "submit-btn-saverecord").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".nowrap:nth-child(4) img").click()
    time.sleep(3)
    self.driver.find_element(By.NAME, "oth_pi_non_id").click()
    self.driver.find_element(By.NAME, "oth_pi_non_id").send_keys("Test")
    self.driver.find_element(By.NAME, "oth_pi_id").click()
    self.driver.find_element(By.NAME, "oth_pi_id").send_keys("Test 2")
    self.driver.find_element(By.ID, "opt-oth_pi_yes_no_0").click()
    self.driver.find_element(By.NAME, "oth_pi_complete").click()
    dropdown = self.driver.find_element(By.NAME, "oth_pi_complete")
    dropdown.find_element(By.XPATH, "//option[. = 'Complete']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\__SUBMITBUTTONS__-div > #submit-btn-saverecord > span").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".nowrap:nth-child(2) > a > img").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#SurveyActionDropDown > span").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".ui-menu-item:nth-child(1) > #surveyoption-openSurvey > span").click()
    self.vars["win5809"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win5809"])
    time.sleep(1)
    self.driver.find_element(By.NAME, "eoi_name").click()
    self.driver.find_element(By.NAME, "eoi_name").send_keys("Test")
    self.driver.find_element(By.NAME, "eoi_email").click()
    self.driver.find_element(By.NAME, "eoi_email").send_keys("nina@x.com")
    self.driver.find_element(By.NAME, "eoi_mobile").click()
    self.driver.find_element(By.NAME, "eoi_mobile").send_keys("07888888888")
    self.driver.find_element(By.NAME, "eoi_date").click()
    self.driver.find_element(By.NAME, "eoi_date").send_keys("07-04-2025")
    self.driver.find_element(By.NAME, "submit-btn-saverecord").click()
    self.driver.find_element(By.CSS_SELECTOR, ".jqbuttonmed > span").click()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".ok-button").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#rsd-men-link > span").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rcgreen:nth-child(1)").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".nowrap:nth-child(2) > a > img").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#\\__SUBMITBUTTONS__-div #submit-btn-savecontinue > span").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > .ui-button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#SurveyActionDropDown > span").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".ui-menu-item:nth-child(1) > #surveyoption-openSurvey > span").click()
    self.vars["win2568"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win2568"])
    self.driver.find_element(By.NAME, "eoi_name").click()
    self.driver.find_element(By.NAME, "eoi_name").send_keys("Test")
    self.driver.find_element(By.NAME, "eoi_email").click()
    self.driver.find_element(By.NAME, "eoi_email").send_keys("nina@x.com")
    self.driver.find_element(By.NAME, "eoi_mobile").click()
    self.driver.find_element(By.NAME, "eoi_mobile").send_keys("07888888888")
    self.driver.find_element(By.NAME, "submit-btn-saverecord").click()
    self.driver.find_element(By.CSS_SELECTOR, ".jqbuttonmed > span").click()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".ok-button").click()
    time.sleep(3)
    self.driver.close()
  
