# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test5ClearPIILogicTestonSave():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_5ClearPIILogicTestonSave(self):
    self.driver.get("https://redcap03.nottingham.ac.uk/redcap_v15.0.10/ProjectSetup/index.php?pid=532")
    self.driver.find_element(By.CSS_SELECTOR, "#rsd-men-link > span").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rcgreen:nth-child(1)").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".nowrap:nth-child(2) > a > img").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#\\__SUBMITBUTTONS__-div #submit-btn-savecontinue > span").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > .ui-button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#SurveyActionDropDown > span").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".ui-menu-item:nth-child(1) > #surveyoption-openSurvey > span").click()
    self.vars["win6240"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6240"])
    self.driver.find_element(By.NAME, "eoi_name").click()
    self.driver.find_element(By.NAME, "eoi_name").send_keys("Test")
    self.driver.find_element(By.NAME, "eoi_email").click()
    self.driver.find_element(By.NAME, "eoi_email").send_keys("nina@x.com")
    self.driver.find_element(By.CSS_SELECTOR, "#eoi_mobile-tr > .data").click()
    self.driver.find_element(By.NAME, "eoi_mobile").click()
    self.driver.find_element(By.NAME, "eoi_mobile").send_keys("07888888888")
    self.driver.find_element(By.NAME, "eoi_date").click()
    self.driver.find_element(By.NAME, "eoi_date").send_keys("08-04-2025")
    self.driver.find_element(By.NAME, "submit-btn-saverecord").click()
    self.driver.find_element(By.CSS_SELECTOR, ".jqbuttonmed > span").click()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".ok-button").click()
    self.driver.close()
  
