# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test7ManualClearPIIUseraccess():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_7ManualClearPIIUseraccess(self):
    self.driver.get("https://redcap03.nottingham.ac.uk/redcap_v15.0.10/ProjectSetup/index.php?pid=532")
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Clear Discontinued PIIs").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "User Rights").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "msznc (Nina Clayton)").click()
    self.driver.find_element(By.ID, "assignUserBtn3").click()
    self.driver.find_element(By.ID, "user_role").click()
    dropdown = self.driver.find_element(By.ID, "user_role")
    dropdown.find_element(By.XPATH, "//option[. = 'Data Management']").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "assignDagRoleBtn").click()
    self.driver.find_element(By.LINK_TEXT, "Clear Discontinued PIIs").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "User Rights").click()
    time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "msznc (Nina Clayton)").click()
    self.driver.find_element(By.ID, "assignUserBtn3").click()
    self.driver.find_element(By.ID, "user_role").click()
    dropdown = self.driver.find_element(By.ID, "user_role")
    dropdown.find_element(By.XPATH, "//option[. = 'Site Researcher']").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "assignDagRoleBtn").click()
    self.driver.find_element(By.LINK_TEXT, "Clear Discontinued PIIs").click()
    time.sleep(1)
    self.driver.execute_script("window.history.go(-1)")
    self.driver.find_element(By.LINK_TEXT, "User Rights").click()
    self.driver.find_element(By.LINK_TEXT, "msznc (Nina Clayton)").click()
    self.driver.find_element(By.ID, "assignUserBtn3").click()
    self.driver.find_element(By.ID, "user_role").click()
    dropdown = self.driver.find_element(By.ID, "user_role")
    dropdown.find_element(By.XPATH, "//option[. = 'Administrator']").click()
    self.driver.find_element(By.ID, "assignDagRoleBtn").click()
    time.sleep(1)
    self.driver.execute_script("window.history.go(0)")
    self.driver.find_element(By.LINK_TEXT, "Clear Discontinued PIIs").click()
    self.driver.close()
  
