# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test02ClearPIImanually():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_02ClearPIImanually(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Clear PII Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Clear PII Test").click()
    self.driver.find_element(By.LINK_TEXT, "Clear Discontinued PIIs").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "#review-record-button > span").click()
    assert self.driver.switch_to.alert.text == "At least one field must be selected."
    time.sleep(1)
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"3\"]').prop(\'checked\', true);")
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"4\"]').prop(\'checked\', true);")
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"5\"]').prop(\'checked\', true);")
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"6\"]').prop(\'checked\', true);")
    self.driver.find_element(By.CSS_SELECTOR, "#review-record-button > span").click()
    assert self.driver.switch_to.alert.text == "A record id must be entered."
    time.sleep(1)
    self.driver.find_element(By.ID, "clear-record").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "#review-record-button > span").click()
    self.driver.find_element(By.ID, "cancel-clear").click()
    self.driver.find_element(By.CSS_SELECTOR, "#review-record-button > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#clear-record-button > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#review-record-button > span").click()
    time.sleep(1)
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"3\"]').prop(\'checked\', true);")
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"4\"]').prop(\'checked\', true);")
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"5\"]').prop(\'checked\', true);")
    self.driver.execute_script("$(\'[name=\"clear_field[]\"][value=\"6\"]').prop(\'checked\', true);")
    self.driver.find_element(By.ID, "clear-record").click()
    self.driver.find_element(By.ID, "clear-record").send_keys("1")
    self.driver.find_element(By.CSS_SELECTOR, "#review-record-button > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#review-record-button > span").click()
  
