# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test03ManualClearPIIUseraccess():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_03ManualClearPIIUseraccess(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
    self.driver.execute_script("$(\'#username\').val(\'user\');$(\'#password\').val(\'abc123\')")
    self.driver.find_element(By.ID, "login_btn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a[href*=\"index.php?action=myprojects\"]")))
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Clear PII Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".round:nth-child(8) .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".round:nth-child(8) .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > .ui-button:nth-child(2)").click()
    self.driver.find_element(By.ID, "keep_data").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(33) > .ui-dialog-buttonpane .ui-button:nth-child(2)").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"clear_pii\"] .external-modules-configure-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-lg .save").click()
    time.sleep(5)
    print("ECHOSCREENSHOT")
    
