# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01ClearPIILogicTestonSave():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_01ClearPIILogicTestonSave(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Clear PII Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Clear PII Test").click()
    self.driver.find_element(By.CSS_SELECTOR, "#rsd-men-link > span").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rcgreen:nth-child(1)").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".nowrap:nth-child(2) > a > img").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#\\__SUBMITBUTTONS__-div > #submit-btn-saverecord > span").click()
    time.sleep(3)
    print("ECHOSCREENSHOT")
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > .ui-button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\__SUBMITBUTTONS__-div > #submit-btn-saverecord > span").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > .ui-button:nth-child(2)").click()
    time.sleep(3)
    self.driver.execute_script("window.location.href=$(\'[name=\"eoi_url\"]\').val()")
    self.driver.find_element(By.NAME, "eoi_name").click()
    self.driver.find_element(By.NAME, "eoi_name").send_keys("Test")
    self.driver.find_element(By.NAME, "eoi_email").click()
    self.driver.find_element(By.NAME, "eoi_email").send_keys("nina@x.com")
    self.driver.find_element(By.CSS_SELECTOR, "#eoi_mobile-tr > .data").click()
    self.driver.find_element(By.NAME, "eoi_mobile").click()
    self.driver.find_element(By.NAME, "eoi_mobile").send_keys("07888888888")
    self.driver.find_element(By.NAME, "eoi_date").click()
    self.driver.execute_script("$(\'[name=\"eoi_date\"]\').val(\'\')")
    self.driver.find_element(By.NAME, "eoi_date").send_keys("08-04-2025")
    self.driver.find_element(By.NAME, "submit-btn-saverecord").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
    self.driver.execute_script("$(\'#footer\').remove()")
    self.driver.execute_script("window.history.back()")
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Clear PII Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Clear PII Test").click()
    print("ECHOSCREENSHOT")
  
