# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test04ProuctionLogicSave():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_04ProuctionLogicSave(self):
    self.driver.get("http://127.0.0.1/")
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "footer")))
    self.driver.execute_script("$(\'#username\').val(\'admin\');$(\'#password\').val(\'abc123\')")
    self.driver.find_element(By.ID, "login_btn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "a[href*=\"index.php?action=myprojects\"]")))
    self.driver.find_element(By.LINK_TEXT, "My Projects").click()
    elements = self.driver.find_elements(By.XPATH, "//*[@id=\"table-proj_table\"][contains(.,\'Clear PII Test\')]")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Clear PII Test").click()
    time.sleep(5)
    self.driver.execute_script("window.scrollTo(0,306)")
    print("ECHOSCREENSHOT")
    self.driver.find_element(By.CSS_SELECTOR, "button[onclick*=\"MoveToProd()\"]").click()
    self.driver.execute_script("$(\'#south\').remove()")
    self.driver.find_element(By.ID, "keep_data").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Move to Production\')]").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.ID, "south")))
    self.driver.find_element(By.LINK_TEXT, "Manage").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "tr[data-module=\"clear_pii\"] .external-modules-configure-button").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".modal-lg .save").click()
    time.sleep(5)
    self.driver.find_element(By.LINK_TEXT, "Logging").click()
    time.sleep(1)
    print("ECHOSCREENSHOT")
    
